// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/product-service/service/product-option-service.go

// Package service is a generated GoMock package.
package service

import (
	dto "chilindo/src/product-service/dto"
	entity "chilindo/src/product-service/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProductOptionService is a mock of ProductOptionService interface.
type MockProductOptionService struct {
	ctrl     *gomock.Controller
	recorder *MockProductOptionServiceMockRecorder
}

// MockProductOptionServiceMockRecorder is the mock recorder for MockProductOptionService.
type MockProductOptionServiceMockRecorder struct {
	mock *MockProductOptionService
}

// NewMockProductOptionService creates a new mock instance.
func NewMockProductOptionService(ctrl *gomock.Controller) *MockProductOptionService {
	mock := &MockProductOptionService{ctrl: ctrl}
	mock.recorder = &MockProductOptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductOptionService) EXPECT() *MockProductOptionServiceMockRecorder {
	return m.recorder
}

// CreateOption mocks base method.
func (m *MockProductOptionService) CreateOption(b *dto.CreateOptionDTO) (*entity.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOption", b)
	ret0, _ := ret[0].(*entity.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOption indicates an expected call of CreateOption.
func (mr *MockProductOptionServiceMockRecorder) CreateOption(b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOption", reflect.TypeOf((*MockProductOptionService)(nil).CreateOption), b)
}

// DeleteOption mocks base method.
func (m *MockProductOptionService) DeleteOption(b *dto.OptionIdDTO) (*entity.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOption", b)
	ret0, _ := ret[0].(*entity.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOption indicates an expected call of DeleteOption.
func (mr *MockProductOptionServiceMockRecorder) DeleteOption(b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOption", reflect.TypeOf((*MockProductOptionService)(nil).DeleteOption), b)
}

// GetOptionByID mocks base method.
func (m *MockProductOptionService) GetOptionByID(b *dto.OptionIdDTO) (*entity.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptionByID", b)
	ret0, _ := ret[0].(*entity.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptionByID indicates an expected call of GetOptionByID.
func (mr *MockProductOptionServiceMockRecorder) GetOptionByID(b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptionByID", reflect.TypeOf((*MockProductOptionService)(nil).GetOptionByID), b)
}

// GetOptions mocks base method.
func (m *MockProductOptionService) GetOptions(b *dto.ProductIdDTO) (*[]entity.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions", b)
	ret0, _ := ret[0].(*[]entity.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockProductOptionServiceMockRecorder) GetOptions(b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockProductOptionService)(nil).GetOptions), b)
}

// UpdateOption mocks base method.
func (m *MockProductOptionService) UpdateOption(b *dto.UpdateOptionDTO) (*entity.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOption", b)
	ret0, _ := ret[0].(*entity.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOption indicates an expected call of UpdateOption.
func (mr *MockProductOptionServiceMockRecorder) UpdateOption(b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOption", reflect.TypeOf((*MockProductOptionService)(nil).UpdateOption), b)
}
