version: '3'

services:
  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./src/api-gateway:/etc/krakend
    ports:
      - "8080:8080"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
  account:
    container_name: account
    image: auctee/account
    build:
      context: .
      dockerfile: ./src/account-service/Dockerfile
    ports:
      - "1001:1001"
      - "50051:50051"
    environment:
      - DB_USER=root
      - DB_PASS=Ledoan070899
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=aucteev1
      - GIN_PORT=1001
      - GRPC_SERVER_PORT=50051
      - KEY_PAIRS=lEDOAN
      - COOKIE_AUTH=user_token
      - SECRET_KEY=KhoaLuan2022

  product:
    container_name: product
    image: auctee/product
    build:
      context: .
      dockerfile: ./src/product-service/Dockerfile
    ports:
      - "1002:1002"
      - "50052:50052"
    environment:
      - DB_USER=root
      - DB_PASS=Ledoan070899
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=aucteev1
      - GIN_PORT=1002
      - GRPC_SERVER_PORT=50052
      - ACCOUNT_SRV_HOST=account:50051
      - KEY_PAIRS=lEDOAN
      - COOKIE_AUTH=user_token
      - SECRET_KEY=KhoaLuan2022

  auction:
    container_name: auction
    image: auctee/auction
    build:
      context: .
      dockerfile: ./src/auction-service/Dockerfile
    ports:
      - "1009:1009"
      - "50053:50053"
    environment:
      - DB_USER=root
      - DB_PASS=Ledoan070899
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=aucteev1
      - GIN_PORT=1009
      - GRPC_SERVER_PORT=50053
      - ACCOUNT_SRV_HOST=account:50051
      - PRODUCT_SRV_HOST=product:50052
      - KEY_PAIRS=lEDOAN
      - COOKIE_AUTH=user_token
      - SECRET_KEY=KhoaLuan2022
  payment:
    container_name: payment
    image: auctee/payment
    build:
      context: .
      dockerfile: ./src/payment-service/Dockerfile
    ports:
      - "1003:1003"
    environment:
      - DB_USER=root
      - DB_PASS=Ledoan070899
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=aucteev1
      - GIN_PORT=1003
      - ACCOUNT_SRV_HOST=account:50051
      - AUCTION_SRV_HOST=auction:50053
      - KEY_PAIRS=lEDOAN
      - COOKIE_AUTH=user_token
      - SECRET_KEY=KhoaLuan2022
      - MOMO_EP=https://test-payment.momo.vn/v2/gateway/api/create
      - MOMO_ACCESS_KEY=iPXneGmrJH0G8FOP
      - MOMO_SECRET_KEY=sFcbSGRSJjwGxwhhcEktCHWYUuTuPNDB