// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: pkg/proto/account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Authenticate account
type CheckIsAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *CheckIsAuthRequest) Reset() {
	*x = CheckIsAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckIsAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsAuthRequest) ProtoMessage() {}

func (x *CheckIsAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsAuthRequest.ProtoReflect.Descriptor instead.
func (*CheckIsAuthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_account_proto_rawDescGZIP(), []int{0}
}

func (x *CheckIsAuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckIsAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAuth bool `protobuf:"varint,1,opt,name=isAuth,proto3" json:"isAuth,omitempty"`
}

func (x *CheckIsAuthResponse) Reset() {
	*x = CheckIsAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckIsAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsAuthResponse) ProtoMessage() {}

func (x *CheckIsAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsAuthResponse.ProtoReflect.Descriptor instead.
func (*CheckIsAuthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_account_proto_rawDescGZIP(), []int{1}
}

func (x *CheckIsAuthResponse) GetIsAuth() bool {
	if x != nil {
		return x.IsAuth
	}
	return false
}

//Address
type GetAddressByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	AddressId uint32 `protobuf:"varint,2,opt,name=AddressId,proto3" json:"AddressId,omitempty"`
}

func (x *GetAddressByUserIdRequest) Reset() {
	*x = GetAddressByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddressByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressByUserIdRequest) ProtoMessage() {}

func (x *GetAddressByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetAddressByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddressByUserIdRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAddressByUserIdRequest) GetAddressId() uint32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

type GetAddressByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname   string `protobuf:"bytes,1,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname    string `protobuf:"bytes,2,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	Phone       string `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Province    string `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty"`
	District    string `protobuf:"bytes,6,opt,name=District,proto3" json:"District,omitempty"`
	SubDistrict string `protobuf:"bytes,7,opt,name=SubDistrict,proto3" json:"SubDistrict,omitempty"`
	Address     string `protobuf:"bytes,8,opt,name=Address,proto3" json:"Address,omitempty"`
	TypeAddress string `protobuf:"bytes,9,opt,name=TypeAddress,proto3" json:"TypeAddress,omitempty"`
}

func (x *GetAddressByUserIdResponse) Reset() {
	*x = GetAddressByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddressByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressByUserIdResponse) ProtoMessage() {}

func (x *GetAddressByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetAddressByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddressByUserIdResponse) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *GetAddressByUserIdResponse) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *GetAddressByUserIdResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetAddressByUserIdResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetAddressByUserIdResponse) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GetAddressByUserIdResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *GetAddressByUserIdResponse) GetSubDistrict() string {
	if x != nil {
		return x.SubDistrict
	}
	return ""
}

func (x *GetAddressByUserIdResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAddressByUserIdResponse) GetTypeAddress() string {
	if x != nil {
		return x.TypeAddress
	}
	return ""
}

type GetUserByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *GetUserByUserIdRequest) Reset() {
	*x = GetUserByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUserIdRequest) ProtoMessage() {}

func (x *GetUserByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByUserIdRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shopname string `protobuf:"bytes,1,opt,name=Shopname,proto3" json:"Shopname,omitempty"`
}

func (x *GetUserByUserIdResponse) Reset() {
	*x = GetUserByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUserIdResponse) ProtoMessage() {}

func (x *GetUserByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByUserIdResponse) GetShopname() string {
	if x != nil {
		return x.Shopname
	}
	return ""
}

var File_pkg_proto_account_proto protoreflect.FileDescriptor

var file_pkg_proto_account_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x12, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x73, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2d, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73,
	0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x73, 0x41, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73,
	0x41, 0x75, 0x74, 0x68, 0x22, 0x51, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x22, 0x98, 0x02, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x44, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x75, 0x62, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xdf, 0x01, 0x0a, 0x0e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x41, 0x75, 0x74, 0x68, 0x12, 0x13, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a,
	0x12, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_account_proto_rawDescOnce sync.Once
	file_pkg_proto_account_proto_rawDescData = file_pkg_proto_account_proto_rawDesc
)

func file_pkg_proto_account_proto_rawDescGZIP() []byte {
	file_pkg_proto_account_proto_rawDescOnce.Do(func() {
		file_pkg_proto_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_account_proto_rawDescData)
	})
	return file_pkg_proto_account_proto_rawDescData
}

var file_pkg_proto_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_account_proto_goTypes = []interface{}{
	(*CheckIsAuthRequest)(nil),         // 0: CheckIsAuthRequest
	(*CheckIsAuthResponse)(nil),        // 1: CheckIsAuthResponse
	(*GetAddressByUserIdRequest)(nil),  // 2: GetAddressByUserIdRequest
	(*GetAddressByUserIdResponse)(nil), // 3: GetAddressByUserIdResponse
	(*GetUserByUserIdRequest)(nil),     // 4: GetUserByUserIdRequest
	(*GetUserByUserIdResponse)(nil),    // 5: GetUserByUserIdResponse
}
var file_pkg_proto_account_proto_depIdxs = []int32{
	0, // 0: AccountService.CheckIsAuth:input_type -> CheckIsAuthRequest
	2, // 1: AccountService.GetAddressByUserId:input_type -> GetAddressByUserIdRequest
	4, // 2: AccountService.GetUserByUserId:input_type -> GetUserByUserIdRequest
	1, // 3: AccountService.CheckIsAuth:output_type -> CheckIsAuthResponse
	3, // 4: AccountService.GetAddressByUserId:output_type -> GetAddressByUserIdResponse
	5, // 5: AccountService.GetUserByUserId:output_type -> GetUserByUserIdResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_account_proto_init() }
func file_pkg_proto_account_proto_init() {
	if File_pkg_proto_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckIsAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckIsAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddressByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddressByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_account_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_account_proto_goTypes,
		DependencyIndexes: file_pkg_proto_account_proto_depIdxs,
		MessageInfos:      file_pkg_proto_account_proto_msgTypes,
	}.Build()
	File_pkg_proto_account_proto = out.File
	file_pkg_proto_account_proto_rawDesc = nil
	file_pkg_proto_account_proto_goTypes = nil
	file_pkg_proto_account_proto_depIdxs = nil
}
